language: r

r:
  - bioc-release 

# R environment 
r_packages:
  - devtools

before_script:
  - R -e 'devtools::document()'

cache:
  directories:
    - $TRAVIS_BUILD_DIR/R/Library	# cache R build Lib
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
