language: r

r:
  - bioc-release 

before_install:
  - echo "before"

script:
  - echo "after"
  
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
