language: r
r:
- bioc-release
r_packages:
- devtools
- knitr

stages:
  name: build 
  if: branch = develop
      before_script:
    	- R -e 'devtools::document()'
    	- R -e 'devtools::build_vignettes()'
      script:
    	- cd $TRAVIS_BUILD_DIR/../
    	- R CMD build $packageName
    	- R CMD check ${packageName}_*.tar.gz --check-subdirs=yes  
      cache:
    	directories:
    	  - "$HOME/R/Library"
    	  - "$HOME/packrat/src"
    	  - "$HOME/packrat/lib"
      packages: true
      after_success:
    	- cd $TRAVIS_BUILD_DIR
    	- bash .scripts/R_doc.sh
      after_failure:
    	- cd $TRAVIS_BUILD_DIR
    	- bash .scripts/R_debug.sh

script:
  - echo "Hello $TRAVIS_BRANCH"

env:
  global:
  - orgName=DPP4ResearchGroup packageName=SyntenyViz 
  - secure: fiOlChR7kCAL6HP2csNeaJuTV2vzet4t1jtYGrNCmOTD+iao0ReE9FALXlwN3G+YrDEJbpAqrIVoVhmX0j4fBGpecJ1Old/+mWlRLSPsCK0YHFzK3WnEmgvy8A6+GjmCcwZUVZkz2FEdxKvGpQ2Jo1h8kP/Ia9nDIwba/nxjprsosrxe0dds9YN9HL8nhOplz6r5KL7t3w7yKGBRK+bL1FLRP1ODjRmwkYhsMNKAFWvE5aqJN+czceLB0jeCw33wCMc0w0N76badMkquJrn5JW/yP06ocmzjlQA8IjMMlNGEboBDY3u5nodeFWj6IcCwAWQCWKMbuArzSkJ6slnHVduVejefRuCsCIsCiE0sKkNJRPMOsdfVK/9aOKhayQGnYLUqkXbjqpvfC2pS94p/A+/lcSctZFcuyLITn4g7CcI0/SGorNM56QYXcHiM7H+kAgysko2KOirNi39VUItYRvXRQTZCxSQjqbU8YFFQnLXieF9LRlu7jGETZH37lZSUVNYpoakg76SluH5TANkINka4nCJwnfaIzAImma5QGRSM6yDrUgVfKGl3ecYU3YTQqqixLdituj0vr4lOK9+tQ4Rv/V9v4qg8ikvdqqRjEXEFmBCaBnkzjovvjNEQzV2ZSRm14GYujj7DfweG0STpm0FeEJp2HbOo0ywur7eixIc=
  - secure: JruMTNctLAnok2K0BAobPYYrwoZ8KEnyUXIXDKRkIdsCwemttnqR/sKnpzL6s8tlYAUyD24YvbT201cZzbSIpxmWR9Y1O5iAFPP+uE+k7tawXGJw5YyE6Coh+32E78YZHgncC/Cy8z098jzV2zr6QxOjWPvHYbSiyA6WzQFazEmJm3c8amQj3BteRSdoMywmIEhLcRpUkJpcP3plpD0IwlgTajxYq+Rpia2xbcT7tPImOQlcCvRFjQMZGCj7xK2Rz9rxlSG0CmLuKOD0ChwMslxJQm3rB3w8sbb8GeV0lMuMm5cOWEVWvd47aAHoocRl9rUAtuNY3UloWEHYagHEn+f9R8cBpePVIwiJbg2kczmVny11141czCwzu3GrtwCUXROa/mHt6QH1pfMlfMlLy7ML+2k1HSWWWlfOkcbRAAKPlByM9qomSjdv4awm+tJRE6Ay7rcoH8Y+Wss2SGiX9i9mBzZGYtgZKVOP15vOatAWc5+l4ulFyPyShckdV+g1QfHJ6J1k68Qn43PCKxbhXdekqqV/uRx9STv4xa4esHhCww2A44i751x4eAa+DPGNELmXvfyv2OCyPPhBYbSVPE43n7CVpuCxciYvDUlFh8+/jzKyS9rZhqpDDf+Va/9A12Z1iREbH6QcbHMcG5Att1gDnibNdlUsLM9RPVg9Mo4=

## deployment of compiled vignettes to gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $robqbot_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: doc
  name: robqbot
  email: qiao0015@flinders.edu.au
  verbose: true
  on:
    branch: master
  target-branch:
    - gh-pages
