title: SyntenyViz
description: A synteny visulasation R package
show_downloads: true
google_analytics: UA-155344407-1
theme: jekyll-theme-architect

# site variables
github:
  pdf_url: https://github.com/DPP4ResearchGroup/SyntenyViz/tree/gh-pages/jekyll_collection/SyntenyViz_workflow.pdf
  tar_url: 
