#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --checks Links,Images,Scripts --check-sri
bundle exec rubocop -D
bundle exec script/validate-html
gem build jekyll-theme-architect.gemspec
