#' A synvizData object that is used to test the integrity of function \code{synvizData}
#'
#' synvizDataTest is a data.frame that generated by function \code{synvizData}
#' with given orgm = "Hsapiens" and mycoords.list is "2:16e7:16.5e7"
#'
#' @docType data
#'
#' @usage data(synvizDataTest)
#'
#' @format A list object with \code{itrack}, \code{gtrack} and \code{atrack}
#'
#' @keywords datasets
#'
#' @source org.Hs.eg.db and TxDb.Hsapiens.UCSC.hg38.knownGene
#'
#' @family SynvizPlot
#'
#' @examples
#' data(synvizDataTest)
#' itrack <- synvizDataTest$itrack
#' gtrack <- synvizDataTest$gtrack
#' atrack <- synvizDataTest$atrack

"synvizDataTest"
